"""Desenha a folha do cachorro na mesma grade do gato (ADR 0013).

    python tools/arte/desenhar_cachorro.py

Em tons de cinza de proposito: a cor de cada vigia e mecanica (ADR 0010) e chega
por modulate no jogo. Saida: recursos/arte/cachorro.png.
Requer: pip install pillow numpy
"""
from pathlib import Path
from PIL import Image
import numpy as np

RAIZ = Path(__file__).resolve().parents[2]
# o = contorno, b = pelo (tingido), d = pelo escuro, w = claro, n = focinho/nariz,
# e = olho, c = coleira, s = sombra, t = lingua
COR = {'o': (40, 36, 44, 255), 'b': (215, 215, 215, 255), 'd': (150, 150, 155, 255),
       'w': (250, 250, 250, 255), 'n': (20, 18, 22, 255), 'e': (20, 18, 22, 255),
       'c': (200, 40, 50, 255), 's': (110, 110, 110, 150), 't': (235, 120, 140, 255)}
LADO_A = """
.............oo.......
............odo.......
...........odbbooo....
...........obbbbbbo...
..o........obebbwwoo..
.odo.......obbbbwwwno.
.odo.......oobbbwwoo..
..odo.....occcobbto...
...obooooobbbbbbo.....
...obbbbbbbbbbbbo.....
...obbbbbbbbbwwbo.....
...odbbbbbbbbwwbo.....
....obdoooooobdbo.....
....obo.....obo.o.....
...obo......obo.......
...oo.......oo........
..ssssssssssssss......
"""
LADO_B = """
.............oo.......
............odo.......
...........odbbooo....
...........obbbbbbo...
...........obebbwwoo..
..oo.......obbbbwwwno.
.odo.......oobbbwwoo..
.odoo.....occcobbto...
...obooooobbbbbbo.....
...obbbbbbbbbbbbo.....
...obbbbbbbbbwwbo.....
...odbbbbbbbbwwbo.....
....obdoooooobdbo.....
.....obo....obo.......
.....obo.....obo......
.....oo.......oo......
..ssssssssssssss......
"""
FRENTE_A = """
...oo........oo...
..odbo......obdo..
..odbbooooooobdo..
..obbbbbbbbbbbbo..
..obbebbbbbbebbo..
...obbbwwwwbbbo...
...obbwwnnwwbbo...
....obwwttwwbo....
....occcccccco....
...obbbwwwwbbbo...
...obbbwwwwbbbo...
...obbbbbbbbbbo...
...obbobbbbobbo...
...obo.obbo.obo...
...oo..oooo..oo...
..ssssssssssssss..
"""
FRENTE_B = """
...oo........oo...
..odbo......obdo..
..odbbooooooobdo..
..obbbbbbbbbbbbo..
..obbebbbbbbebbo..
...obbbwwwwbbbo...
...obbwwnnwwbbo...
....obwwttwwbo....
....occcccccco....
...obbbwwwwbbbo...
...obbbwwwwbbbo...
...obbbbbbbbbbo...
...obbobbbbobbo...
...obo.obbo.oo....
...oo..oooo.......
..ssssssssssssss..
"""
COSTAS_A = """
...oo........oo...
..odbo......obdo..
..odbbooooooobdo..
..obbbbbbbbbbbbo..
..obbbbbbbbbbbbo..
...obbbbbbbbbbo...
...odbbbbbbbbdo...
....obbbbbbbbo....
....occcccccco....
...obbbbbbbbbbo...
...obbbbddbbbbo...
...obbbbddbbbbo...
...obbobddbobbo...
...obo.odo..obo...
...oo...o....oo...
..ssssssssssssss..
"""
COSTAS_B = """
...oo........oo...
..odbo......obdo..
..odbbooooooobdo..
..obbbbbbbbbbbbo..
..obbbbbbbbbbbbo..
...obbbbbbbbbbo...
...odbbbbbbbbdo...
....obbbbbbbbo....
....occcccccco....
...obbbbbbbbbbo...
...obbbbddbbbbo...
...obbbbddbbbbo...
...obbobddbobbo...
...oo..odo..obo...
........o....oo...
..ssssssssssssss..
"""
PARADO_A = FRENTE_A
PARADO_B = FRENTE_A.replace("....obwwttwwbo....", "....obwwwwwwbo....")
F = 24
def quadro(txt, espelhar=False):
    linhas = [l for l in txt.strip('\n').split('\n')]
    w = max(len(l) for l in linhas); h = len(linhas)
    q = np.zeros((F, F, 4), np.uint8)
    oy = F - h - 1; ox = (F - w) // 2
    for y, l in enumerate(linhas):
        for x, ch in enumerate(l.ljust(w, '.')):
            if ch != '.':
                xx = (w - 1 - x) if espelhar else x
                q[oy + y, ox + xx] = COR[ch]
    return q
# mesma grade do gato: baixo, direita, cima, esquerda, parado (4 quadros cada)
linhas = [
    [FRENTE_A, FRENTE_B, FRENTE_A, FRENTE_B.replace("...obo.obbo.oo....", "....oo.obbo.obo...").replace("...oo..oooo.......", ".......oooo..oo...")],
    [(LADO_A, False), (LADO_B, False)] * 2,
    [COSTAS_A, COSTAS_B, COSTAS_A, COSTAS_B.replace("...oo..odo..obo...", "...obo.odo..oo....").replace("........o....oo...", "...oo...o.........")],
    [(LADO_A, True), (LADO_B, True)] * 2,
    [PARADO_A, PARADO_A, PARADO_B, PARADO_B],
]
folha = np.zeros((F * 5, F * 4, 4), np.uint8)
for r, fila in enumerate(linhas):
    for c, item in enumerate(fila):
        txt, esp = item if isinstance(item, tuple) else (item, False)
        folha[r*F:(r+1)*F, c*F:(c+1)*F] = quadro(txt, esp)
Image.fromarray(folha, 'RGBA').save(RAIZ / 'recursos/arte/cachorro.png')
print('gravado recursos/arte/cachorro.png')
